/*
 * font8x16.h - 8x16 bitmap font (ASCII 32..126), generated by tools/gen_font.py.
 *
 * SPDX-License-Identifier: MIT
 */
#ifndef RJS_FONT8X16_H
#define RJS_FONT8X16_H

#include <stdint.h>

#define RJS_FONT_WIDTH  8
#define RJS_FONT_HEIGHT 16
#define RJS_FONT_FIRST  32
#define RJS_FONT_LAST   126
#define RJS_FONT_GLYPHS (RJS_FONT_LAST - RJS_FONT_FIRST + 1)

extern const uint8_t rjs_font8x16[RJS_FONT_GLYPHS][RJS_FONT_HEIGHT];

#endif /* RJS_FONT8X16_H */
