#!/usr/bin/env python3
"""
gen_font.py - generate the 8x16 bitmap font used by common/ui.

Renders ASCII 32..126 from DejaVu Sans Mono into a C array (one byte per pixel
row, MSB = leftmost pixel) and writes common/ui/src/font8x16.c.

    python3 tools/gen_font.py [path-to-ttf]

Re-run only when the font should change; the generated file is committed so a
normal build needs no Python and no font files.

SPDX-License-Identifier: MIT
"""
import sys

from PIL import Image, ImageDraw, ImageFont

DEFAULT_TTF = "/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf"
FIRST, LAST = 32, 126
W, H = 8, 16
OUT = "common/ui/src/font8x16.c"

HEADER = """/*
 * font8x16.c - 8x16 bitmap font, ASCII 32..126.
 *
 * GENERATED by tools/gen_font.py from DejaVu Sans Mono - do not edit by hand.
 * The DejaVu fonts are released under a permissive license (Bitstream Vera /
 * Arev derivative); see THIRD_PARTY_NOTICES.md.
 *
 * One byte per pixel row, bit 7 = leftmost pixel.
 */
#include "rjs/font8x16.h"

const uint8_t rjs_font8x16[RJS_FONT_GLYPHS][RJS_FONT_HEIGHT] = {
"""


def main() -> int:
    ttf = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_TTF
    font = ImageFont.truetype(ttf, 15)
    lines = [HEADER]
    for code in range(FIRST, LAST + 1):
        img = Image.new("1", (W, H), 0)
        d = ImageDraw.Draw(img)
        d.text((0, -1), chr(code), font=font, fill=1)
        rows = []
        for y in range(H):
            byte = 0
            for x in range(W):
                if img.getpixel((x, y)):
                    byte |= 0x80 >> x
            rows.append(f"0x{byte:02X}")
        ch = chr(code).replace("\\", "\\\\").replace("'", "\\'")
        lines.append(f"    {{{', '.join(rows)}}},   /* '{ch}' */\n")
    lines.append("};\n")
    with open(OUT, "w", encoding="utf-8") as f:
        f.writelines(lines)
    print(f"wrote {OUT}: {LAST - FIRST + 1} glyphs, {(LAST - FIRST + 1) * H} bytes")
    return 0


if __name__ == "__main__":
    sys.exit(main())
